// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAY_w9JAhfXkAi0bZe655h3EiskybNs-L4',
    appId: '1:766215119997:web:32d212b89e693d2c92fd14',
    messagingSenderId: '766215119997',
    projectId: 'expensemonitorflutter',
    authDomain: 'expensemonitorflutter.firebaseapp.com',
    storageBucket: 'expensemonitorflutter.appspot.com',
    measurementId: 'G-VM2MRYH98P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEU3JmPMv7a9qxQyKsfKzWSJNnbyr7eEw',
    appId: '1:766215119997:android:dad3055f5d90fbf192fd14',
    messagingSenderId: '766215119997',
    projectId: 'expensemonitorflutter',
    storageBucket: 'expensemonitorflutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiYYzzLH-m4K6krdV6m4QQA4docGdzX8s',
    appId: '1:766215119997:ios:93de4ab30b3ead0e92fd14',
    messagingSenderId: '766215119997',
    projectId: 'expensemonitorflutter',
    storageBucket: 'expensemonitorflutter.appspot.com',
    iosBundleId: 'com.example.flutterSample1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiYYzzLH-m4K6krdV6m4QQA4docGdzX8s',
    appId: '1:766215119997:ios:e01d402c32d44f4e92fd14',
    messagingSenderId: '766215119997',
    projectId: 'expensemonitorflutter',
    storageBucket: 'expensemonitorflutter.appspot.com',
    iosBundleId: 'com.example.flutterSample1.RunnerTests',
  );
}
